#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := wolfssl_client

CFLAGS += -DWOLFSSL_USER_SETTINGS

include $(IDF_PATH)/make/project.mk

