.PHONY: all
all:
	+$(MAKE) -C wolfssl-wolfcrypt

.PHONY: test
test:
	+$(MAKE) -C wolfssl-wolfcrypt test

.PHONY: testfips
testfips:
	+$(MAKE) -C wolfssl-wolfcrypt testfips

.PHONY: clean
clean:
	+$(MAKE) -C wolfssl-wolfcrypt clean
