@echo off
setlocal

REM --- These paths are tied to a specific e2studio/CCRX install (plugin version, CCRX
REM version, platform ID) and will not exist as-is on a different machine or a different
REM e2studio/CCRX version. Set MAKE/CCRX_BIN/E2_UTILS in the environment before calling
REM build.bat to override the defaults below for your install. ---
if not defined MAKE set MAKE=C:\Renesas\e2_studio\eclipse\plugins\com.renesas.ide.exttools.gnumake.win32.x86_64_4.3.1.v20240909-0854\mk\make.exe
if not defined CCRX_BIN set CCRX_BIN=C:\PROGRA~2\Renesas\RX\3_6_0\bin
if not defined E2_UTILS set E2_UTILS=%USERPROFILE%\.eclipse\com.renesas.platform_1435879475\Utilities\ccrx
set PATH=%CCRX_BIN%;%E2_UTILS%;%PATH%
set BASEDIR=%~dp0

set TARGET=all
set MODE=
if /i "%1"=="clean" (
    set TARGET=clean
) else if /i "%1"=="crypt" (
    set MODE=crypt
) else if /i "%1"=="bench" (
    set MODE=bench
) else if /i "%1"=="TLSClient" (
    set MODE=TLSClient
) else if not "%1"=="" (
    echo [ERROR] Unknown argument "%1".
    echo Usage: build.bat [clean^|crypt^|bench^|TLSClient]
    echo   crypt      -^> enables #define CRYPT_TEST in wolfssl_simple_demo.h
    echo   bench      -^> enables #define BENCHMARK
    echo   TLSClient  -^> enables #define SIMPLE_TLS_TSIP_CLIENT
    exit /b 1
)

if not "%MODE%"=="" (
    echo ============================================================
    echo  Setting demo mode: %MODE%
    echo ============================================================
    powershell -NoProfile -ExecutionPolicy Bypass -File "%BASEDIR%set_demo_mode.ps1" -Mode %MODE%
    if %ERRORLEVEL% neq 0 (
        echo [ERROR] Failed to set demo mode.
        exit /b %ERRORLEVEL%
    )
    echo.
)

REM --- Both makefile(s) below are generated by e2studio's managed-build system (from
REM .cproject) the first time each project is built there; build.bat only does incremental
REM rebuilds on top of that, it cannot bootstrap them from a truly clean checkout. ---
if not exist "%BASEDIR%wolfssl\Debug\makefile" (
    echo [ERROR] "%BASEDIR%wolfssl\Debug\makefile" not found.
    echo Open the "wolfssl" project in e2studio and build the "Debug" configuration once
    echo ^(Project ^> Build Project^) to generate it, then re-run build.bat.
    exit /b 1
)
if not exist "%BASEDIR%test\HardwareDebug\makefile" (
    echo [ERROR] "%BASEDIR%test\HardwareDebug\makefile" not found.
    echo Open the "test" project in e2studio and build the "HardwareDebug" configuration once
    echo ^(Project ^> Build Project^) to generate it, then re-run build.bat.
    exit /b 1
)
if not exist "%BASEDIR%test\src\smc_gen" (
    echo [ERROR] "%BASEDIR%test\src\smc_gen" not found.
    echo This is generated by e2studio's Smart Configurator from test.scfg ^(not tracked in
    echo git^). Open test.scfg in e2studio and click "Generate Code" once, then re-run build.bat.
    exit /b 1
)

echo ============================================================
echo  wolfssl library  [%TARGET%]
echo ============================================================
cd /d "%BASEDIR%wolfssl\Debug"
"%MAKE%" %TARGET%
if %ERRORLEVEL% neq 0 (
    echo [ERROR] wolfssl build failed.
    exit /b %ERRORLEVEL%
)

echo.
echo ============================================================
echo  test application  [%TARGET%]
echo ============================================================
cd /d "%BASEDIR%test\HardwareDebug"
"%MAKE%" %TARGET%
if %ERRORLEVEL% neq 0 (
    echo [ERROR] test build failed.
    exit /b %ERRORLEVEL%
)

echo.
echo ============================================================
echo  Done.
echo ============================================================
endlocal
