/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the Seeed MT3620 Mini Development Board (MDB) to the
// 'template appliance' abstraction used by the templates.
// Some peripherals are on-board on the Seeed MT3620 MDB, while other peripherals must be
// attached externally if needed.
// See https://aka.ms/AzureSphereHardwareDefinitions for more information on how to use
// hardware abstractions to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../template_appliance.json.  Do not edit it directly.

#pragma once
#include "seeed_mt3620_mdb.h"

// MT3620 MDB: User LED.
#define TEMPLATE_LED SEEED_MT3620_MDB_USER_LED

