@echo off
REM EnableDelayedExpansion is required below: MAKE/ARM_GCC_BIN/E2_BUSYBOX are filesystem
REM paths that may contain literal parens (e.g. "Program Files (x86)"). A parenthesized
REM if-block reads its %VAR% references and substitutes them at block-PARSE time, before
REM any line in the block runs -- so echoing one with %VAR% reintroduces raw, unescaped
REM parens into the block's text and corrupts cmd.exe's block-boundary parsing (that's
REM what broke here: caret-escaping the SET line alone isn't enough, because the escape
REM is consumed once by SET and the stored value has no escaping left for later %-expansions).
REM !VAR! (delayed expansion) instead resolves at each line's execution time, after the
REM block has already been parsed, so it never reintroduces the problem.
setlocal EnableDelayedExpansion

REM --- These paths are tied to a specific e2studio/GNU ARM Embedded install (plugin
REM version, toolchain version, platform ID) and will not exist as-is on a different
REM machine or install. Set MAKE/ARM_GCC_BIN/E2_BUSYBOX in the environment before calling
REM build.bat to override the defaults below for your install. ---
set USING_DEFAULTS=
if not defined MAKE (
    set MAKE=C:\Renesas\e2_studio\eclipse\plugins\com.renesas.ide.exttools.gnumake.win32.x86_64_4.3.1.v20240909-0854\mk\make.exe
    set USING_DEFAULTS=1
)
REM The default path below has literal parens in "Program Files (x86)". Inside an
REM if-block, cmd.exe's parser stops the block at the FIRST unescaped closing paren it
REM meets -- not a properly nested count -- so an unescaped ")" here would truncate the
REM block right after "(x86" and run the rest of the line as a stray command. Must stay
REM caret-escaped as ^( and ^) below; do not "clean up" this escaping.
if not defined ARM_GCC_BIN (
    set ARM_GCC_BIN=C:\Program Files ^(x86^)\Arm GNU Toolchain arm-none-eabi\13.3 rel1\bin
    set USING_DEFAULTS=1
)
REM Generated makefiles call BusyBox "rm"/"xargs" directly (not via a shell), so this
REM directory must be on PATH or the clean recipe fails with
REM "process_begin: CreateProcess(NULL, rm ...) failed".
if not defined E2_BUSYBOX (
    set E2_BUSYBOX=C:\Renesas\e2_studio\eclipse\plugins\com.renesas.ide.exttools.busybox.win32.x86_64_1.3.6.v20230615-0931\bin
    set USING_DEFAULTS=1
)
if defined USING_DEFAULTS (
    echo [NOTICE] MAKE/ARM_GCC_BIN/E2_BUSYBOX is not set. Using default paths below;
    echo these are tied to one specific e2studio/toolchain install and will likely not
    echo exist on a different machine or install. Please adjust the paths for your
    echo environment by setting these variables before running build.bat.
    echo   MAKE        = !MAKE!
    echo   ARM_GCC_BIN = !ARM_GCC_BIN!
    echo   E2_BUSYBOX  = !E2_BUSYBOX!
    echo.
    pause
)
set PATH=%ARM_GCC_BIN%;%E2_BUSYBOX%;%PATH%
set BASEDIR=%~dp0

set TARGET=all
set MODE=
set FORCE_WOLFSSL_REBUILD=
if /i "%1"=="clean" (
    set TARGET=clean
) else if /i "%1"=="crypt" (
    set MODE=crypt
) else if /i "%1"=="bench" (
    set MODE=bench
) else if /i "%1"=="TLSClient" (
    set MODE=TLSClient
) else if /i "%1"=="wolfssl" (
    set FORCE_WOLFSSL_REBUILD=1
) else if not "%1"=="" (
    echo [ERROR] Unknown argument "%1".
    echo Usage: build.bat [clean^|crypt^|bench^|TLSClient^|wolfssl]
    echo   crypt      -^> enables #define CRYPT_TEST in common\wolfssl_demo.h
    echo   bench      -^> enables #define BENCHMARK
    echo   TLSClient  -^> enables #define TLS_CLIENT
    echo   wolfssl    -^> force-rebuild files that depend on user_settings.h
    echo                ^(and other shared wolfSSL headers^) after editing it.
    echo                The generated makefiles only track each .c's own
    echo                mtime, not the headers it includes, so plain
    echo                incremental "build.bat" silently keeps stale objects;
    echo                "build.bat clean" catches it too but also nukes and
    echo                recompiles the untouched SEGGER RTT plumbing, which
    echo                takes longer than the wolfSSL-facing side alone.
    exit /b 1
)

if not "%MODE%"=="" (
    echo ============================================================
    echo  Setting demo mode: %MODE%
    echo ============================================================
    powershell -NoProfile -ExecutionPolicy Bypass -File "%BASEDIR%set_demo_mode.ps1" -Mode %MODE%
    if %ERRORLEVEL% neq 0 (
        echo [ERROR] Failed to set demo mode.
        exit /b %ERRORLEVEL%
    )
    echo.
)

REM --- Both makefile(s) below are generated by e2studio's managed-build system (from
REM .cproject) the first time each project is built there; build.bat only does incremental
REM rebuilds on top of that, it cannot bootstrap them from a truly clean checkout. ---
if not exist "%BASEDIR%wolfssl\Debug\makefile" (
    echo [ERROR] "%BASEDIR%wolfssl\Debug\makefile" not found.
    echo Open the "wolfssl" project in e2studio and build the "Debug" configuration once
    echo ^(Project ^> Build Project^) to generate it, then re-run build.bat.
    exit /b 1
)
if not exist "%BASEDIR%test\Debug\makefile" (
    echo [ERROR] "%BASEDIR%test\Debug\makefile" not found.
    echo Open the "test" project in e2studio and build the "Debug" configuration once
    echo ^(Project ^> Build Project^) to generate it, then re-run build.bat.
    exit /b 1
)
if not exist "%BASEDIR%wolfssl\ra_gen" (
    echo [ERROR] "%BASEDIR%wolfssl\ra_gen" not found.
    echo This is generated by e2studio's FSP Configurator from wolfssl's configuration.xml
    echo ^(not tracked in git^). Open configuration.xml in e2studio and click "Generate
    echo Project Content" once, then re-run build.bat.
    exit /b 1
)

REM Below, "if errorlevel 1" (not "if %ERRORLEVEL% neq 0") is required to check the clean
REM step's exit code: %ERRORLEVEL% inside a parenthesized if-block is expanded once when
REM the whole block is parsed, before "%MAKE%" clean has even run, so it would always
REM read as whatever it was beforehand and silently ignore a failed clean. "if errorlevel"
REM is a distinct construct that re-checks the real, current value at that point instead.
if defined FORCE_WOLFSSL_REBUILD (
    echo ============================================================
    echo  wolfssl library  [clean rebuild]
    echo ============================================================
    cd /d "%BASEDIR%wolfssl\Debug"
    "%MAKE%" clean
    if errorlevel 1 (
        echo [ERROR] wolfssl clean failed.
        exit /b 1
    )
) else (
    echo ============================================================
    echo  wolfssl library  [%TARGET%]
    echo ============================================================
    cd /d "%BASEDIR%wolfssl\Debug"
)
"%MAKE%" %TARGET%
if %ERRORLEVEL% neq 0 (
    echo [ERROR] wolfssl build failed.
    exit /b %ERRORLEVEL%
)

echo.
if defined FORCE_WOLFSSL_REBUILD (
    echo ============================================================
    echo  test application  [selective rebuild: wolfSSL-facing sources only,
    echo  SEGGER RTT plumbing left untouched]
    echo ============================================================
    cd /d "%BASEDIR%test\Debug"
    for %%F in (
        src\test_main.o
        src\wolf_client.o
        src\wolfssl_sce_unit_test.o
        src\sce_tst_thread_entry.o
        src\test.o
        src\benchmark.o
        key_data\key_data_sce.o
    ) do (
        if exist "%%F" del /f /q "%%F"
    )
) else (
    echo ============================================================
    echo  test application  [%TARGET%]
    echo ============================================================
    cd /d "%BASEDIR%test\Debug"
)
"%MAKE%" %TARGET%
if %ERRORLEVEL% neq 0 (
    echo [ERROR] test build failed.
    exit /b %ERRORLEVEL%
)

set MAPFILE=%BASEDIR%test\Debug\test_RA6M4.map
set RTT_ADDR=
REM _SEGGER_RTT is the RTT control block (SEGGER_RTT.c, placed in its own ".txt.rtt_block"
REM section). J-Link RTT Viewer/JLinkGDBServer can auto-search RAM for it, but that's slow
REM and occasionally picks up stale/aliased data; giving it this address directly is faster
REM and unambiguous. Only meaningful after a real link ("all"), not after "clean".
if /i "%TARGET%"=="all" if exist "%MAPFILE%" (
    for /f "tokens=1" %%A in ('findstr /c:"_SEGGER_RTT" "%MAPFILE%"') do set RTT_ADDR=%%A
    echo.
    echo ============================================================
    if defined RTT_ADDR (
        echo  RTT control block ^(_SEGGER_RTT^) address: !RTT_ADDR!
        echo  Use this in J-Link RTT Viewer / JLinkGDBServer's RTT "Address" field to
        echo  skip the auto-search.
    ) else (
        echo  [WARN] Could not find _SEGGER_RTT in %MAPFILE%.
    )
    echo ============================================================
)

echo.
echo ============================================================
echo  Done.
echo ============================================================
endlocal
