/* x509v3.h for openssl */

typedef struct WOLFSSL_AUTHORITY_KEYID {
    WOLFSSL_ASN1_STRING *string;
    GENERAL_NAME *name;
    WOLFSSL_ASN1_INTEGER *integer;
} WOLFSSL_AUTHORITY_KEYID;
#define AUTHORITY_KEYID     WOLFSSL_AUTHORITY_KEYID

#define ASN1_INTEGER        WOLFSSL_ASN1_INTEGER
#define ASN1_OCTET_STRING   WOLFSSL_ASN1_STRING
