/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the Avnet MT3620 Starter Kit (SK) to the
// 'template appliance' abstraction used by the templates.
// Some peripherals are on-board on the Avnet MT3620 SK, while other peripherals must be
// attached externally if needed.
// See https://aka.ms/AzureSphereHardwareDefinitions for more information on how to use
// hardware abstractions to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../template_appliance.json.  Do not edit it directly.

#pragma once
#include "avnet_mt3620_sk.h"

// MT3620 SK: User LED.
#define TEMPLATE_LED AVNET_MT3620_SK_USER_LED_RED

