name: MSYS2 Build Test

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: ucrt64,  compiler: mingw-w64-ucrt-x86_64-gcc }
          - { sys: mingw64, compiler: mingw-w64-x86_64-gcc }
          - { sys: msys, compiler: gcc }
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: git ${{matrix.compiler}} autotools base-devel autoconf netcat
      - name: configure wolfSSL
        run: ./autogen.sh && ./configure CFLAGS="-DUSE_CERT_BUFFERS_2048 -DUSE_CERT_BUFFERS_256 -DNO_WRITE_TEMP_FILES"
      - name: build wolfSSL
        run: make check
      - name: Display log
        if: always()
        run: cat test-suite.log
