#ifndef WOLFSSL_DSP_INC
#define WOLFSSL_DSP_INC

#include "AEEStdDef.idl"
#include "remote.idl"

interface wolfSSL: remote_handle64{

	/* ecc operations */
    long DSP_ECC_Verify(in sequence<uint8>  hash, inrout sequence<uint8> x963,
            inrout sequence<uint8> rdsp, inrout sequence<uint8> sdsp,
            in long curveId, inrout long res, inrout sequence<uint8> cache);
};
#endif
