<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyName>wolfCrypt-FIPS-Test</AssemblyName>
    <RootNamespace>wolfSSL.CSharp.Fips.Test</RootNamespace>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../wolfCrypt-FIPS/wolfCrypt-FIPS.csproj" />
  </ItemGroup>

</Project>
