/* gen_frodokem.c
 *
 * Copyright (C) 2006-2026 wolfSSL Inc.
 *
 * This file is part of wolfSSL.
 *
 * wolfSSL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfSSL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

/* Generator for the FrodoKEM test key material in this directory.
 *
 * FrodoKEM is a KEM, and neither OpenSSL nor the liboqs oqs-provider expose it
 * as a certificate/key-encoding algorithm with the ISO/IEC 18033-2 OIDs that
 * wolfSSL uses (their FrodoKEM integration is KEM-only, for TLS key exchange).
 * These fixtures therefore cannot be produced with OpenSSL the way the ML-DSA
 * material is; they are generated by wolfSSL itself using wc_MakeCert_ex() and
 * friends. A KEM public key cannot sign, so the certificate and request are
 * signed by an ECC (P-256) issuer key.
 *
 * Material is produced for the 976 and 1344 (SHAKE) parameter sets; 640 has no
 * standardised OID and cannot be encoded.
 *
 * Build against an installed wolfSSL configured with (at least):
 *   --enable-experimental --enable-frodokem --enable-certgen --enable-certreq
 *   --enable-certext --enable-keygen --enable-ecc  (and HAVE_PKCS8,
 *   WOLFSSL_DER_TO_PEM)
 *
 *   cc gen_frodokem.c -lwolfssl -o gen_frodokem && (cd certs/frodokem &&
 *       ./gen_frodokem)
 */

#include <wolfssl/options.h>
#include <wolfssl/wolfcrypt/settings.h>
#include <wolfssl/wolfcrypt/wc_frodokem.h>
#include <wolfssl/wolfcrypt/asn_public.h>
#include <wolfssl/wolfcrypt/ecc.h>
#include <wolfssl/wolfcrypt/random.h>
#include <stdio.h>
#include <string.h>

#if !defined(WOLFSSL_HAVE_FRODOKEM) || defined(WOLFSSL_FRODOKEM_NO_ASN1) || \
    !defined(WOLFSSL_CERT_GEN) || !defined(WOLFSSL_CERT_REQ) || \
    !defined(WOLFSSL_CERT_EXT) || !defined(HAVE_ECC) || \
    !defined(WOLFSSL_DER_TO_PEM)
int main(void)
{
    fprintf(stderr, "wolfSSL not built with the features needed to generate "
                    "the FrodoKEM certificates (see the header comment).\n");
    return 1;
}
#else

static byte der[45000];
static byte pem[64000];
static byte caDer[4000];

static int writeFile(const char* name, const byte* data, int len)
{
    FILE* f;
    if (len <= 0) {
        fprintf(stderr, "  %s: nothing to write (%d)\n", name, len);
        return -1;
    }
    f = fopen(name, "wb");
    if (f == NULL) {
        fprintf(stderr, "  cannot open %s\n", name);
        return -1;
    }
    (void)fwrite(data, 1, (size_t)len, f);
    fclose(f);
    printf("  wrote %s (%d bytes)\n", name, len);
    return 0;
}

/* Convert DER to PEM and write it, guarding against a bad DER length. */
static void writePem(const byte* d, int derLen, int pemType, const char* name)
{
    int plen;
    if (derLen <= 0) {
        fprintf(stderr, "  %s: bad DER length (%d)\n", name, derLen);
        return;
    }
    plen = wc_DerToPem(d, (word32)derLen, pem, sizeof(pem), pemType);
    writeFile(name, pem, plen);
}

/* Only set the string fields; wc_InitCert() already zeroed the struct and set
 * the per-field ASN encoding types, which must be preserved. */
static void setName(CertName* n, const char* cn)
{
    XSTRNCPY(n->country, "US", CTC_NAME_SIZE);
    n->countryEnc = CTC_PRINTABLE;
    XSTRNCPY(n->state, "Montana", CTC_NAME_SIZE);
    n->stateEnc = CTC_UTF8;
    XSTRNCPY(n->locality, "Bozeman", CTC_NAME_SIZE);
    n->localityEnc = CTC_UTF8;
    XSTRNCPY(n->org, "wolfSSL", CTC_NAME_SIZE);
    n->orgEnc = CTC_UTF8;
    XSTRNCPY(n->unit, "Test", CTC_NAME_SIZE);
    n->unitEnc = CTC_UTF8;
    XSTRNCPY(n->commonName, cn, CTC_NAME_SIZE);
    n->commonNameEnc = CTC_UTF8;
}

/* Generate the key, public SPKI, ECC-signed leaf certificate and ECC-signed
 * certificate request for one FrodoKEM parameter set. */
static int genVariant(WC_RNG* rng, ecc_key* ca, int caLen, int type,
                      const char* prefix, const char* cn)
{
    FrodoKemKey fk;
    Cert cert;
    char fn[128];
    int len, body;

    if (wc_FrodoKemKey_Init(&fk, type, NULL, INVALID_DEVID) != 0) {
        fprintf(stderr, "FrodoKEM key init failed for %s\n", prefix);
        return -1;
    }
    if (wc_FrodoKemKey_MakeKey(&fk, rng) != 0) {
        fprintf(stderr, "FrodoKEM key generation failed for %s\n", prefix);
        wc_FrodoKemKey_Free(&fk);
        return -1;
    }

    /* Private key (PKCS#8) and public key (SubjectPublicKeyInfo). */
    len = wc_FrodoKemKey_PrivateKeyToDer(&fk, der, sizeof(der));
    XSNPRINTF(fn, sizeof(fn), "%s-key.der", prefix);
    writeFile(fn, der, len);
    XSNPRINTF(fn, sizeof(fn), "%s-key.pem", prefix);
    writePem(der, len, PKCS8_PRIVATEKEY_TYPE, fn);
    len = wc_FrodoKemKey_PublicKeyToDer(&fk, der, sizeof(der), 1);
    XSNPRINTF(fn, sizeof(fn), "%s_pub-spki.der", prefix);
    writeFile(fn, der, len);

    /* Leaf certificate signed by the ECC CA. */
    wc_InitCert(&cert);
    setName(&cert.subject, cn);
    setName(&cert.issuer, "FrodoKEM Test ECC CA");
    cert.sigType = CTC_SHA256wECDSA;
    cert.selfSigned = 0;   /* issuer is the ECC CA, not the subject */
    cert.daysValid = 36500;   /* long-lived test fixture */
    (void)wc_SetSubjectKeyIdFromPublicKey_ex(&cert, FRODOKEM_TYPE, &fk);
    (void)wc_SetAuthKeyIdFromCert(&cert, caDer, caLen);
    body = wc_MakeCert_ex(&cert, der, sizeof(der), FRODOKEM_TYPE, &fk, rng);
    if (body > 0) {
        len = wc_SignCert(body, CTC_SHA256wECDSA, der, sizeof(der), NULL, ca,
                          rng);
        XSNPRINTF(fn, sizeof(fn), "%s-cert.der", prefix);
        writeFile(fn, der, len);
        XSNPRINTF(fn, sizeof(fn), "%s-cert.pem", prefix);
        writePem(der, len, CERT_TYPE, fn);
    }

    /* Certificate request signed by the ECC key (a KEM cannot self-sign). */
    wc_InitCert(&cert);
    setName(&cert.subject, cn);
    cert.sigType = CTC_SHA256wECDSA;
    cert.version = 0;   /* PKCS#10 (RFC 2986) requires version 0 */
    body = wc_MakeCertReq_ex(&cert, der, sizeof(der), FRODOKEM_TYPE, &fk);
    if (body > 0) {
        len = wc_SignCert(body, CTC_SHA256wECDSA, der, sizeof(der), NULL, ca,
                          rng);
        XSNPRINTF(fn, sizeof(fn), "%s-req.der", prefix);
        writeFile(fn, der, len);
        XSNPRINTF(fn, sizeof(fn), "%s-req.pem", prefix);
        writePem(der, len, CERTREQ_TYPE, fn);
    }

    wc_FrodoKemKey_Free(&fk);
    return 0;
}

int main(void)
{
    WC_RNG rng;
    ecc_key ca;
    Cert cert;
    int ret = 0;
    int len;
    int body;
    int caLen = 0;

    if (wc_InitRng(&rng) != 0) {
        fprintf(stderr, "RNG init failed\n");
        return 1;
    }

    /* ---- Issuer: self-signed ECC P-256 CA ---- */
    if (wc_ecc_init(&ca) != 0) {
        fprintf(stderr, "ECC CA init failed\n");
        ret = 1; goto out_rng;
    }
    if (wc_ecc_make_key(&rng, 32, &ca) != 0) {
        fprintf(stderr, "ECC CA key generation failed\n");
        wc_ecc_free(&ca);
        ret = 1; goto out_rng;
    }
    wc_InitCert(&cert);
    setName(&cert.subject, "FrodoKEM Test ECC CA");
    cert.sigType = CTC_SHA256wECDSA;
    cert.isCA = 1;
    cert.selfSigned = 1;
    cert.daysValid = 36500;   /* long-lived test fixture */
    (void)wc_SetSubjectKeyIdFromPublicKey_ex(&cert, ECC_TYPE, &ca);
    body = wc_MakeCert_ex(&cert, caDer, sizeof(caDer), ECC_TYPE, &ca, &rng);
    if (body > 0) {
        len = wc_SignCert(body, CTC_SHA256wECDSA, caDer, sizeof(caDer), NULL,
                          &ca, &rng);
        caLen = len;
        writeFile("frodokem-ca-ecc-cert.der", caDer, len);
        writePem(caDer, len, CERT_TYPE, "frodokem-ca-ecc-cert.pem");
    }
    len = wc_EccKeyToDer(&ca, der, sizeof(der));
    writeFile("frodokem-ca-ecc-key.der", der, len);
    writePem(der, len, ECC_PRIVATEKEY_TYPE, "frodokem-ca-ecc-key.pem");

    /* ---- FrodoKEM parameter sets with a standardised OID ---- */
    (void)genVariant(&rng, &ca, caLen, WC_FRODOKEM_976_SHAKE, "frodokem976",
                     "FrodoKEM-976");
    (void)genVariant(&rng, &ca, caLen, WC_FRODOKEM_1344_SHAKE, "frodokem1344",
                     "FrodoKEM-1344");

    wc_ecc_free(&ca);
out_rng:
    wc_FreeRng(&rng);
    return ret;
}

#endif
