name: WolfSSL Ada Build Tests

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    if: github.repository_owner == 'wolfssl'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install alire
      uses: alire-project/setup-alire@v5

    - name: Build wolfssl Ada
      working-directory: ./wrapper/Ada
      run: |
        alr exec -- gprbuild -j$(nproc) default.gpr
        alr exec -- gprbuild -j$(nproc) examples.gpr

    - name: Run Ada wrapper tests (alire)
      working-directory: ./wrapper/Ada
      run: |
        alr install
        cd tests
        alr run

    - name: Run Ada wrapper tests (valgrind)
      working-directory: ./wrapper/Ada/tests
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind
        valgrind --leak-check=full --error-exitcode=1 \
          --suppressions=valgrind.supp ./bin/tests
