name: PUF Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  puf_host_test:
    name: PUF host test
    if: github.repository_owner == 'wolfssl'
    runs-on: ubuntu-24.04
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
        name: Checkout wolfSSL

      - name: Build and test PUF
        run: |
          ./autogen.sh
          ./configure --enable-puf --enable-puf-test
          make
          ./wolfcrypt/test/testwolfcrypt

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
